### ISSUE TITLE
Pictures_for_focus5

### ISSUE THREAD

**Issue by emilylxf** [CSEN-SCU/a3-beta-version-with-user-feedback-focusfive#10]
<img width="1182" alt="Screen Shot 2023-05-16 at 3 20 04 PM" src="https://github.com/COEN-296-Attention-Management-Spr-2023/a3-beta-version-with-user-feedback-focusfive/assets/49005820/cf294306-8938-47e5-8971-a82c891fe4c7">

**Comment by Joanne-Chang** [comment]
cool
