### ISSUE TITLE
Optional: Be able to remove individual sites from the List

### ISSUE THREAD

**Issue by Joanne-Chang** [CSEN-SCU/a3-beta-version-with-user-feedback-focusfive#32]
![Untitled chrome extension](https://github.com/COEN-296-Attention-Management-Spr-2023/a3-beta-version-with-user-feedback-focusfive/assets/23194620/61456e65-6036-49ac-9015-771a02c2d29e)

The "remove site" X buttons on the Lists currently do not work. Optional: Fix this. Or: Delete this.

**Comment by emilylxf** [comment]
Done
